def get_sys_prompt():
    return """As a professional security engineer,your task is to develop a Python script that generates a new test casefile.\
This file should adhere to the format required by the fuzzing harness code and pass the specified constraint in the snippet.\
The script will play a crucial role in creating diverse and effective test cases for thorough security testing."""


def get_prefix():
    return """```python\n"""


def get_suffix():
    return """if __name__ == __main__ :
    if(len(sys.argv)<2):
        print("usage: python3 generator.py <output_path>")
        sys.exit(1)
    # Some setup codes
    with open(sys.argv[1],'wb') as f:
        case_generator(f)
```"""


def first_prompt(code_snippet, callee, bcode):
    return f"""## STEPS:
1. Understand the core functionality of the program from the code snippet.
2. Analyze the key constraints in the call chain execution and use them to guide subsequent steps.
3. Hypothetically analyze What characteristics does seeds need to meet to meet these constraints. You should consider all of the key constraints.
4. Provide the python script that can generate seeds satisfying these constraints. Remember the generated seeds should functioning correctly.

## code snippet
```{code_snippet}```
the bottleneck constraint is ```{bcode}``` in function ```{callee}```.
As an integrated component of an automated system , you should \
perform the tasks without seeking human confirmation or \
help.
## Instructions
The script should:
1. enclosed with ``` ```.
2. include the full valid Python script in your response.
3. Has one argument , which is the output file path.
4. Generate one test case and write it to the output file.
5. The generated test case should be compatible with the fuzzing harness code provided and pass the specified constraint in the snippet.
## Example
```python
# Some libraries that should be imported
def case_generator(out):
    # generative process of cases
if **name** == **main** :
    if(len(sys.argv)<2):
        print("usage: python3 generator.py <output_path>")
        sys.exit(1)
    # Some setup codes
    with open(sys.argv[1],'wb') as f:
        case_generator(f)
```"""


def fix_prompt(generator, stderr):
    return f"""You generated the following Python code, but it encounters some issues
during execution and raises an error. Please modify the code to make it
run correctly and optimize it where possible. Below are the code and the
error message:

### Code:
{generator}

### Error Message:
{stderr}

Please address the following in your response:
1. Fix the error in the code so that it runs correctly.
2. If possible, optimize the code for better performance, readability, or logic.
3. DON'T provide any explanations for the changes made. just give the python code in the following format:
```python
<your code here>
```"""


def coverage_prompt(coverage):
    return f"""```
{coverage}
```
The number of times the seed generated by the generator covers each line of code is marked with "//coverage:" after the code.
please give some suggestions to help generator breaking through the bottleneck mentioned above, including:
- A 2-3 short sentences summary of the relationship between the script and the coverage. For example, "The script not cover part X because it generates only Y type of data."
- A 2-3 short sentences general guideline on how to improve the script based on the coverage information received. You don’t need to provide a new script, just some advice on how to improve the current one.
"""


def both_no_cover_improve_prompt(generator, coverage, bottleneck_code, funcname):
    return f'''You have generated a generator to finish the task, but the final goal for the generator is to break the roadblock \
located in the line ```{bottleneck_code}``` in function ```{funcname}```. But the case that generated by the script even didn't reach the roadblock. \
The generator script is as follows:
```python
{generator}
```
and the coverage information of the generator is as follows:''' + coverage_prompt(coverage)


def breakthrough_improve_prompt(generator, coverage, bottleneck_code, funcname, not_cover):
    return f'''You have generated a generator to finish the task, but the final goal for the generator is to break the bottleneck \
located in the line ```{bottleneck_code}``` in function ```{funcname}```. The branch that has not been run begins at line ```{not_cover}```. \
The generator script is as follows:
```python
{generator}
```
The specific code coverage is as follows:\n''' + coverage_prompt(coverage)


def improve_generator_with_advice_prompt(generator, coverage, advice):
    return f"""Here is a seed generation script:
```
{generator}
```
Our coverage report indicates that the generated seeds with this script cover parts of the code:
```
{coverage}
```
(In the report,static functions and initializers are marked as uncovered. This is intentional,as these elements are not meant to be included in fuzzer coverage.)
To enhance code coverage,consider refining the script to produce more effective seeds. Here is someadvice to help you improve the script:
```
{advice}
```"""
